baseURL = 'https://stmatthewstoledo.org'
languageCode = 'en-us'
title = "St. Matthew's Anglican Church - Toledo, OH"

[params]
  description = "Welcome to St. Matthew's Anglican Church in Toledo, Ohio. Join us for worship, fellowship, and community."
  phone = "(567) 343-0757"
  email = "StMatthewsACT@gmail.com"
  address = "(Meeting at Toledo First Seventh-day Adventist Church)<br>4909 W. Sylvania Ave.<br>Toledo, OH 43623"
  pastor = "Father Zeke Coughlin"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
